name: untitled7
description: A new Flutter project.
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.12.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  firebase_auth: "^1.0.3"
  get: ^4.6.5
  firebase_core: ^1.21.1


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true
